name: github_client
description: A new Flutter macOS desktop app integrating GitHub GraphQL Client.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  gql: ^1.0.0
  gql_exec: ^1.0.0
  gql_http_link: ^1.0.0
  gql_link: ^1.0.0
  http: ^1.2.1
  oauth2: ^2.0.1
  url_launcher: ^6.1.10
  window_to_front:
    path: window_to_front

dev_dependencies:
  build_runner: ^2.3.3
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  flutter_test:
    sdk: flutter
  gql_build: ^0.13.1

flutter:
  uses-material-design: true
