name: window_to_front
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowToFrontPlugin
      macos:
        pluginClass: WindowToFrontPlugin
      windows:
        pluginClass: WindowToFrontPlugin
